### ISSUE TITLE
Feature: Add messages by group

### ISSUE THREAD

**Issue by Lyrians** [axelrindle/Broadcaster-Plugin#24]
My English is not very good, but I hope I can express myself correctly.

I wanted to offer a new feature for the plugin, and it is to send messages to specific groups, if the group is not specified, then the message will be global.

For example:

```
Messages:
	global:
		- "blabla"
		- "blabla2"
		- "blabla3"

	vip:
		- "only vip"
		- "only vip2"
		- "only vip3"

  - Type: json
    Definition: json_vip
    Group: vip
```
